app = "coflnet-monitor"
primary_region = "iad"

[build]
  builder = "heroku/buildpacks:20"

[env]
  PORT = "3000"
  POLL_INTERVAL = "20000"

[processes]
  web = "node server.js"
  poller = "node poller.js"

[[services]]
  internal_port = 3000
  protocol = "tcp"
  processes = ["web"]

  [[services.ports]]
    handlers = ["http"]
    port = 80
    force_https = true

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
  processes = ["web", "poller"]
