app = "coflnet-monitor"
primary_region = "iad"

[build]
  builder = "heroku/buildpacks:20"

[env]
  PORT = "3000"
  POLL_INTERVAL = "20000"

[processes]
  web = "node server.js"
  poller = "node poller.js"

[[services]]
  protocol = "tcp"
  internal_port = 3000
  processes = ["web"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
  processes = ["web", "poller"]
